FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY kafka/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY kafka/weather_alerts.py .

# Run the alerts consumer
CMD ["python", "weather_alerts.py"]
