FROM apache/flink:1.17

USER root

# Cài Python và pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Cài thư viện Python
COPY requirements.txt /tmp/
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

CMD ["bash"]
