version: 2

models:
  - name: my_model
    description: "Model chứa dữ liệu đã được lọc và xử lý."
    columns:
      - name: id
        description: "ID duy nhất của bản ghi."
        tests:
          - unique
          - not_null
      - name: name
        description: "Tên của đối tượng."
        tests:
          - not_null
          - accepted_values:
              values: ['ValidName1', 'ValidName2', 'ValidName3']
      - name: created_at
        description: "Ngày tạo bản ghi."
        tests:
          - not_null
          - accepted_values:
              values: ['2021-01-01', '2021-01-02', '2021-01-03']
