version: '3'
services:
  dbt:
    build: .
    volumes:
      - .:/dbt_project
    ports:
      - "8080:8080"
    command: tail -f /dev/null
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
