version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spark-app:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  pgdata:
